data = [
    "In early 2015, Apple became the first ever $700 billion company. More recently, Apple overtook Google as the most valuable brand in the world.",
    "You might think of them only as fierce competitors, but Apple and Samsung have a different sort of relationship. Samsung actually manufactures the retina display on the Apple iPad and a portion of the memory chips used in the iPhone 6 (though Apple has cut back on its reliance on Samsung).",
    "In June 2014, a seven-for-one stock split took the trading price of Apple from approximately $645 to $94.",
    " One of the original Apple computers sold for more than $387,000 in 2013.",
    " Apple’s initial public offering was made on December 12, 1980. The company sold 4.6 million shares at a cost of $22 per share.",
    "Apple used the capital from its initial public offering for the development of the Macintosh and Lisa.",
    "The iPhone was almost named something else, with the company considering names such as Mobi, Telepod, and Tripod. The name “iPad” was also considered for its smartphone.",
    "China is currently Apple’s second biggest market, trailing only the United States. Revenue in China grew to nearly $17 billion in the second quarter of 2015.",
    "Despite the fact that he was the founder of the company, Steve Jobs was fired from Apple in 1985 at the tender age of 30.",
    "Apple cracked into the Fortune 500 in 1983, a spot it has held onto ever since.",
    "Apple is pretty secretive. The company is said to have created fake projects for employees and management to work on. If the news leaks, you can hit the road. They’ll know exactly who spilled the beans.",
    "It cost $666.66 to build the first Apple computer. Despite the many conspiracy theories, it has not been proven that anybody at Apple worshipped the devil during production.",
    "Fake Apple retail stores have been opened (and shut down) in many parts of China. In Kunming, for example, these stores appeared so authentic that even employees were duped.",
    "Apple CEO Tim Cook earned $9 million in 2014. A large number, for sure, but not when you consider that Apple is the most valuable company in the world.",
    "The original Apple logo was designed by co-founder Ronald Wayne, who worked at Atari along with Steve Jobs and Steve Wozniak, and is nothing like the one the company uses today.",
    "At one point, Apple did not have the option to market its iPhone in Brazil, as another company owned the trademark. IGM Electronics, a telecommunications company, was the thorn in Apple’s side until the iPhone maker won a trademark case in the country.",
    "Ronald Wayne, the forgotten Apple co-founder, sold his shares in the company in 1977 for $800. While he only owned 10 percent of the company at the time, in today’s world this would be worth tens of billions of dollars. He has noted that he does not regret this decision.",
    "Apple finished 2014 with $178 billion in marketable securities and cash. Even so, CEO Tim Cook is persistent in saying the company doesn’t want a cash hoard.",
    "The revenue generated by Apple is more than the GDP of many countries, including Ecuador, Libya, and Iraq (among hundreds of others).",
    "Apple’s profit for every iPhone 6 Plus sold is approximately $85 more than its smaller counterpart.",
    "In 2005, there were 116 Apple retail stores scattered throughout the world, with the largest number in the United States. This total reached 317 by 2010 and 437 by 2014. The number of Apple stores has increased each year since 2005. Want to go work at one? Good luck–you have a better chance of getting into Harvard!",
]

SKILL_NAME = "iFacts"
GET_FACT_MESSAGE = "Here's your Apple fact: "
HELP_MESSAGE = "You can say tell me an Apple fact, or, you can say exit... What can I help you with?"
HELP_REPROMPT = "What can I help you with?"
STOP_MESSAGE = "Goodbye!"
